id: AF4892835
title: Aspiration to Be Reborn in the Realm of Sukhāvatī
type: translation
pechas:
- I68C70843
- IA028782C
- I92D3D631
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:40:07.267362
  last_modified_at: 2023-01-04 12:40:07.267377
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I68C70843/602B: 86D9
  IA028782C/6A44: 86D9
  I92D3D631/1AB4: 86D9
